      - name: Scrape FANY
        run: |
          python scraper.py

          if [ ! -f new_events.json ]; then
            echo "new_events.json が無いため空配列を作成します"
            echo "[]" > new_events.json
          fi

          echo "=== generated files ==="
          ls -la

          echo "=== new_events.json ==="
          cat new_events.json
      - name: Notify LINE
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TO: ${{ secrets.LINE_TO }}
        run: |
          python notify_line.py

      - name: Save updated events
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add events.json
          git diff --cached --quiet || git commit -m "Update FANY events"
          git push
